# Generated by Django 3.2.4 on 2021-07-25 09:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutblog', '0002_auto_20210712_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutblog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='content',
        ),
        migrations.AlterField(
            model_name='aboutblog',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutblog',
            name='disclaimer',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutblog',
            name='policy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
